import type { Db } from "@paperclipai/db";
import type { DashboardAnalytics, WorkflowAnalytics } from "@paperclipai/shared";
import { dashboardService } from "./dashboard.js";

const QUADRANT_LABELS: Record<string, { label: string; description: string }> = {
  Q1: { label: "Healthy", description: "High completion, low corrections" },
  Q2: { label: "Polishing needed", description: "High completion, high corrections" },
  Q3: { label: "Underutilized or blocked", description: "Low completion, low corrections" },
  Q4: { label: "Broken", description: "Low completion, high corrections" },
};

function formatWorkflowRow(wf: WorkflowAnalytics): string {
  const completionPct = Math.round(wf.completionRate * 100);
  const correctionPct = Math.round(wf.correctionRate * 100);
  const status = wf.quadrant;
  return `| ${wf.workflowType} | ${wf.runsTotal} | ${wf.runsCompleted} | ${completionPct}% | ${wf.correctionsTotal} | ${correctionPct}% | ${status} |`;
}

export function analyticsReportService(db: Db) {
  const dashboard = dashboardService(db);

  return {
    generateMarkdown: async (companyId: string, windowDays = 14): Promise<string> => {
      const summary = await dashboard.summary(companyId);
      const analytics = summary.analytics;
      const generatedAt = new Date().toISOString().split("T")[0];

      const lines: string[] = [
        `# Agent Analytics Report — ${generatedAt}`,
        "",
        `> Window: last ${windowDays} days · Company: ${companyId.slice(0, 8)}`,
        "",
        "## Summary",
        "",
        `| Metric | Value |`,
        `|--------|-------|`,
        `| Total runs | ${analytics.runsTotal} |`,
        `| Completed runs | ${analytics.runsCompleted} |`,
        `| Failed runs | ${analytics.runsFailed} |`,
        `| Overall completion rate | ${Math.round(analytics.completionRate * 100)}% |`,
        `| Total corrections | ${analytics.correctionsTotal} |`,
        "",
        "## Quadrant Breakdown",
        "",
      ];

      for (const q of ["Q1", "Q2", "Q3", "Q4"] as const) {
        const meta = QUADRANT_LABELS[q];
        const items = analytics.quadrants[q] ?? [];
        lines.push(`### ${q}: ${meta.label}`);
        lines.push("");
        lines.push(`${meta.description}`);
        lines.push("");
        if (items.length === 0) {
          lines.push("_No workflows in this quadrant._");
        } else {
          lines.push(items.map(w => `- ${w}`).join("\n"));
        }
        lines.push("");
      }

      lines.push("## Per-Workflow Detail");
      lines.push("");
      lines.push(`| Workflow | Runs | Completed | Completion | Corrections | Correction Rate | Quadrant |`);
      lines.push(`|----------|------|-----------|------------|-------------|-----------------|----------|`);

      for (const wf of analytics.workflows) {
        lines.push(formatWorkflowRow(wf));
      }

      if (analytics.workflows.length === 0) {
        lines.push("| — | — | — | — | — | — | — |");
      }

      lines.push("");
      lines.push("---");
      lines.push("");
      lines.push("*Generated by Paperclip Agent Analytics — Phase 3*");
      lines.push("");

      return lines.join("\n");
    },

    summary: async (companyId: string) => {
      return dashboard.summary(companyId);
    },
  };
}
